/* 
 * This file is part of mcngd - the Mediacenter Next Generation Daemon
 *   (https://github.com/marioli/loewe-mediacenter-mcngd)
 * Copyright (c) 2017 Mario Lombardo
 * 
 * mcngd is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU Lesser General Public License as   
 * published by the Free Software Foundation, version 3.
 *
 * mcngd is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __MLGUARD_MCNG_XML_H
#define __MLGUARD_MCNG_XML_H


/* mcng_xml_gettoc
 *
 * this function reads an XML file generated by the fireball software on the
 * mediacenter and extracts the TOC as a string. On error this function returns
 * NULL. The string must be freed by the caller.
 */
char *mcng_xml_gettoc(const char *filename);


#endif
